export const seedModules = [
  {
    examBoard: "generic" as const,
    moduleCode: "ALGO-01",
    moduleName: "Algorithms",
    topicName: "Computational Thinking & Decomposition",
    topicType: "theory" as const,
    description: "Decomposition, abstraction, and algorithmic thinking fundamentals",
    specReferences: ["J277 2.1", "AQA 3.3.1"],
    difficultyBands: ["easy", "medium", "hard"] as ("easy" | "medium" | "hard")[],
    sortOrder: 1,
  },
  {
    examBoard: "generic" as const,
    moduleCode: "ALGO-02",
    moduleName: "Algorithms",
    topicName: "Searching and Sorting",
    topicType: "theory" as const,
    description: "Linear search, binary search, bubble sort, merge sort, insertion sort",
    specReferences: ["J277 2.1.1", "AQA 3.3.2"],
    difficultyBands: ["easy", "medium", "hard"] as ("easy" | "medium" | "hard")[],
    sortOrder: 2,
  },
  {
    examBoard: "generic" as const,
    moduleCode: "PROG-01",
    moduleName: "Programming Fundamentals",
    topicName: "Variables, Input/Output and Data Types",
    topicType: "programming" as const,
    description: "Variables, constants, data types, input/output in Python",
    specReferences: ["J277 2.2.1", "AQA 3.3.3"],
    difficultyBands: ["easy", "medium", "hard"] as ("easy" | "medium" | "hard")[],
    sortOrder: 3,
  },
  {
    examBoard: "generic" as const,
    moduleCode: "PROG-02",
    moduleName: "Programming Fundamentals",
    topicName: "Sequence, Selection and Iteration",
    topicType: "programming" as const,
    description: "if/elif/else, for loops, while loops, nested structures in Python",
    specReferences: ["J277 2.2.2", "AQA 3.3.3"],
    difficultyBands: ["easy", "medium", "hard"] as ("easy" | "medium" | "hard")[],
    sortOrder: 4,
  },
  {
    examBoard: "generic" as const,
    moduleCode: "PROG-03",
    moduleName: "Programming Fundamentals",
    topicName: "Functions and Subprograms",
    topicType: "programming" as const,
    description: "Defining and calling functions, parameters, return values, scope",
    specReferences: ["J277 2.2.3", "AQA 3.3.4"],
    difficultyBands: ["easy", "medium", "hard"] as ("easy" | "medium" | "hard")[],
    sortOrder: 5,
  },
  {
    examBoard: "generic" as const,
    moduleCode: "PROG-04",
    moduleName: "Programming Fundamentals",
    topicName: "Lists, Strings and File Handling",
    topicType: "programming" as const,
    description: "Lists, string methods, file read/write, defensive design",
    specReferences: ["J277 2.2.4", "AQA 3.3.5"],
    difficultyBands: ["easy", "medium", "hard"] as ("easy" | "medium" | "hard")[],
    sortOrder: 6,
  },
  {
    examBoard: "generic" as const,
    moduleCode: "DATA-01",
    moduleName: "Data Representation",
    topicName: "Binary, Units and Character Sets",
    topicType: "theory" as const,
    description: "Binary numbers, hexadecimal, units of data, ASCII and Unicode",
    specReferences: ["J277 1.4", "AQA 3.2.6"],
    difficultyBands: ["easy", "medium", "hard"] as ("easy" | "medium" | "hard")[],
    sortOrder: 7,
  },
  {
    examBoard: "generic" as const,
    moduleCode: "NET-01",
    moduleName: "Networks",
    topicName: "Network Types, Protocols and Security",
    topicType: "theory" as const,
    description: "LAN/WAN, topologies, TCP/IP, HTTP, cybersecurity basics",
    specReferences: ["J277 1.3", "AQA 3.2.4"],
    difficultyBands: ["easy", "medium", "hard"] as ("easy" | "medium" | "hard")[],
    sortOrder: 8,
  },
  {
    examBoard: "generic" as const,
    moduleCode: "SYS-01",
    moduleName: "Computer Systems",
    topicName: "Hardware, CPU and Memory",
    topicType: "theory" as const,
    description: "CPU architecture, fetch-decode-execute, RAM/ROM, storage types",
    specReferences: ["J277 1.1", "AQA 3.2.1"],
    difficultyBands: ["easy", "medium", "hard"] as ("easy" | "medium" | "hard")[],
    sortOrder: 9,
  },
];
