export const seedTopics = [
  { area: "Fundamentals", areaSortOrder: 1, name: "Variables & assignment", slug: "variables-assignment", sortOrder: 1, description: "Declaring variables, assignment, and updating values in Python." },
  { area: "Fundamentals", areaSortOrder: 1, name: "Data types & casting", slug: "data-types-casting", sortOrder: 2, description: "int, float, str, bool and converting between them." },
  { area: "Fundamentals", areaSortOrder: 1, name: "Input & output", slug: "input-output", sortOrder: 3, description: "Reading input() and printing formatted output." },
  { area: "Fundamentals", areaSortOrder: 1, name: "Operators", slug: "operators", sortOrder: 4, description: "Arithmetic, comparison and logical operators and precedence." },
  { area: "Fundamentals", areaSortOrder: 1, name: "Program structure", slug: "program-structure", sortOrder: 5, description: "Statements, comments, indentation and readable layout." },
  { area: "Selection", areaSortOrder: 2, name: "if / else", slug: "if-else", sortOrder: 1, description: "Branching with if and else." },
  { area: "Selection", areaSortOrder: 2, name: "elif chains", slug: "elif-chains", sortOrder: 2, description: "Multi-way selection with elif." },
  { area: "Selection", areaSortOrder: 2, name: "Nested selection", slug: "nested-selection", sortOrder: 3, description: "if statements inside other if statements." },
  { area: "Selection", areaSortOrder: 2, name: "Boolean conditions", slug: "boolean-conditions", sortOrder: 4, description: "Combining conditions with and, or, not." },
  { area: "Iteration", areaSortOrder: 3, name: "for loops & range", slug: "for-loops-range", sortOrder: 1, description: "Definite iteration with for and range()." },
  { area: "Iteration", areaSortOrder: 3, name: "while loops", slug: "while-loops", sortOrder: 2, description: "Indefinite iteration with while and conditions." },
  { area: "Iteration", areaSortOrder: 3, name: "Nested loops", slug: "nested-loops", sortOrder: 3, description: "Loops inside loops and their trace behaviour." },
  { area: "Iteration", areaSortOrder: 3, name: "break / continue", slug: "break-continue", sortOrder: 4, description: "Controlling loop flow with break and continue." },
  { area: "Strings", areaSortOrder: 4, name: "Indexing & slicing", slug: "string-indexing-slicing", sortOrder: 1, description: "Accessing characters and substrings." },
  { area: "Strings", areaSortOrder: 4, name: "String methods", slug: "string-methods", sortOrder: 2, description: "upper, lower, split, strip, replace and friends." },
  { area: "Strings", areaSortOrder: 4, name: "Traversal & building", slug: "string-traversal-building", sortOrder: 3, description: "Looping over and constructing strings." },
  { area: "Strings", areaSortOrder: 4, name: "f-string formatting", slug: "f-string-formatting", sortOrder: 4, description: "Formatting output with f-strings." },
  { area: "Lists & Data Structures", areaSortOrder: 5, name: "List basics", slug: "list-basics", sortOrder: 1, description: "Creating, indexing and appending lists." },
  { area: "Lists & Data Structures", areaSortOrder: 5, name: "Traversal & aggregation", slug: "list-traversal-aggregation", sortOrder: 2, description: "Summing, counting and finding over lists." },
  { area: "Lists & Data Structures", areaSortOrder: 5, name: "2D lists", slug: "two-d-lists", sortOrder: 3, description: "Lists of lists and grid/table access." },
  { area: "Lists & Data Structures", areaSortOrder: 5, name: "Dictionaries", slug: "dictionaries", sortOrder: 4, description: "Key-value storage and lookup." },
  { area: "Lists & Data Structures", areaSortOrder: 5, name: "Tuples & sets", slug: "tuples-sets", sortOrder: 5, description: "Immutable sequences and unique collections." },
  { area: "Functions & Subprograms", areaSortOrder: 6, name: "Defining & calling", slug: "defining-calling", sortOrder: 1, description: "Writing def and calling functions." },
  { area: "Functions & Subprograms", areaSortOrder: 6, name: "Parameters & arguments", slug: "parameters-arguments", sortOrder: 2, description: "Passing values into functions." },
  { area: "Functions & Subprograms", areaSortOrder: 6, name: "Return values", slug: "return-values", sortOrder: 3, description: "Returning results from functions." },
  { area: "Functions & Subprograms", areaSortOrder: 6, name: "Scope", slug: "scope", sortOrder: 4, description: "Local vs global variables." },
  { area: "Files & Exceptions", areaSortOrder: 7, name: "Reading files", slug: "reading-files", sortOrder: 1, description: "Opening and reading text files." },
  { area: "Files & Exceptions", areaSortOrder: 7, name: "Writing files", slug: "writing-files", sortOrder: 2, description: "Writing and appending to files." },
  { area: "Files & Exceptions", areaSortOrder: 7, name: "try / except", slug: "try-except", sortOrder: 3, description: "Handling runtime errors gracefully." },
  { area: "Files & Exceptions", areaSortOrder: 7, name: "Validation & defensive design", slug: "validation-defensive-design", sortOrder: 4, description: "Validating input and defensive checks." },
  { area: "Algorithms", areaSortOrder: 8, name: "Linear & binary search", slug: "linear-binary-search", sortOrder: 1, description: "Searching lists two ways." },
  { area: "Algorithms", areaSortOrder: 8, name: "Bubble / insertion / merge sort", slug: "sorting-algorithms", sortOrder: 2, description: "Classic sorting algorithms." },
  { area: "Algorithms", areaSortOrder: 8, name: "Counting & accumulation", slug: "counting-accumulation", sortOrder: 3, description: "Running totals, counters and max/min patterns." },
  { area: "Algorithms", areaSortOrder: 8, name: "Tracing & debugging", slug: "tracing-debugging", sortOrder: 4, description: "Predicting output and fixing broken code." },
];
